#!/usr/bin/env python

import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import dot_init
import services.database.session
import services.clusters

import click

@click.group()
def cli():
    pass


@click.command()
@click.option("--name", default=None, required=True, help="server name")
def create(name: str):
    """ create cluster """

    _print_status("cluster create")

    with services.database.session.get() as db_session:
        cluster = services.clusters.create(
            db_session=db_session,
            name=name,
        )

        _print_ok(f"cluster create ok - name '{cluster.name}'")


def _print_error(s: str):
    print("\x1b[1;31m" + s + "\x1b[0m", flush=True)


def _print_ok(s: str):
    print("\x1b[1;32m" + s + "\x1b[0m", flush=True)


def _print_status(s: str):
    print("\x1b[1;36m" + s + "\x1b[0m", flush=True)


cli.add_command(create)


if __name__ == "__main__":
    cli()