name: notme-paas
services:
  # postgres:
  #   container_name: postgres-dev
  #   image: postgis/postgis:14-3.3
  #   network_mode: host
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_PASSWORD: development
  #     POSTGRES_USER: postgres
  #   ports:
  #     - 5433:5432
  #   volumes:
  #     - ~/data:/data

  nats:
    container_name: nats-dev
    image: nats:latest
    network_mode: host
    ports:
      - 4222:4222
      - 8222:8222
    restart: unless-stopped

  redis:
    container_name: redis-dev
    image: redis:latest
    network_mode: host
    ports:
      - 6379:6379
    restart: unless-stopped

  qdrant:
    container_name: qdrant-dev
    image: qdrant/qdrant
    network_mode: host
    ports:
      - 6333:6333
    restart: unless-stopped
    volumes:
      - ~/data/qdrant:/qdrant/storage

  typesense:
    container_name: typesense-dev
    command: ["/opt/typesense-server", "--api-key=xyz", "--enable-cors"]
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data
    image: typesense/typesense:26.0 
    network_mode: host
    ports:
      - 8108:8108
    restart: unless-stopped
    volumes:
      - ~/data:/data

volumes:
  postgres: {}
  qdrant: {}