#!/usr/bin/env python

import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import dot_init
import services.hetzner.ssh_keys

import click

@click.group()
def cli():
    pass


@click.command()
def list():
    """ list ssh keys """

    ssh_keys_struct = services.hetzner.ssh_keys.list()

    for index, ssh_key in enumerate(ssh_keys_struct.objects):
        _print_status(f"ssh key {index+1}: '{ssh_key.name}'")

    _print_ok("ssh keys ok")


def _print_ok(s: str):
    print("\x1b[1;32m" + s + "\x1b[0m", flush=True)

def _print_status(s: str):
    print("\x1b[1;36m" + s + "\x1b[0m", flush=True)


cli.add_command(list)


if __name__ == "__main__":
    cli()